power_full <- read.csv("./household_power_consumption.txt", header=TRUE, sep =";", na.strings = "?")
power <- subset(power_full, Date == '1/2/2007' | Date == '2/2/2007')
png(file = "plot1.png", width = 480, height = 480)
hist(power$Global_active_power, col="red", xlab = "Global Active Power (kilowatts)", main = "Global Active Power")
dev.off()